// flow-typed signature: 1bec7e3b561531a76e865139c4bbb00e
// flow-typed version: <<STUB>>/lodash.map_v4.6.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.map/index' {
  declare module.exports: $Exports<'lodash.map'>;
}
declare module 'lodash.map/index.js' {
  declare module.exports: $Exports<'lodash.map'>;
}
